name: "Automoton Deploy"
description: "Deploy a docker compose project to Automoton on Linode"
inputs:
  project:
    description: "name of the project at automtoton"
    required: false
  token:
    description: "authentication token for automoton"
    required: true
  url:
    description: "Base url for automoton api"
    required: true
  compose:
    description: "Arguments to pass to docker compose"
    required: false
    default: ""
  deploy:
    description: "Should this actually deploy"
    required: false
    default: "true"
outputs: {}
runs:
  using: "node16"
  main: "dist/index.js"
